{
    'name': 'Course Management System',
    'version': '1.0',
    'category': 'Education',
    'summary': 'Manage courses, students, enrollments, instructors, sessions, exams, and payments',
    'description': 'Production-grade Course Management System for Odoo 17',
    'author': 'Nasratullah Shafiq',
    'depends': ['base','mail','account'],
    'data': [
        # 'security/ir.model.access.csv',
        # 'security/record_rules.xml',
        # 'data/sequence_data.xml',
        # 'data/demo_data.xml',
        # 'views/menu_views.xml',
        # 'views/course_category_views.xml',
        # 'views/course_views.xml',
        # 'views/course_material_views.xml',
        # 'views/student_views.xml',
        # 'views/instructor_views.xml',
        # 'views/session_views.xml',
        # 'views/enrollment_views.xml',
        # 'views/exam_views.xml',
        # 'views/result_views.xml',
        # 'views/payment_views.xml',
        # 'report/course_report_templates.xml',
        # 'report/course_reports.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
